In [2]:
import matplotlib.pyplot as plt
import numpy as np


In [4]:
class Polynomial:
  # Constructor, note that it starts and ends with two underscores
  def __init__(self, coeff):
    '''
    Every internal variable of the object must be saved and initialized
    in this method: self.variable = value
    '''
    self.coeff = coeff
    self.degree = len(coeff) - 1

  # Constructor to make the object callable
  def __call__(self, x_arr):
    '''
    Here we assumed x_arr is a numpy array. Remember that a numpy array acts
    like a vector (1D matrix). So an operation x + 1 would add 1 to each element
    of the matrix (unlike python's defaule list). Simlarly, x ** 2 would return
    element wise square of the array.

    Hence, this method would return an array, where the i'th element is the
    (polynomial) interpolated value of x[i], given the coeffecients a[i].
    '''
    p_x_arr = np.zeros(len(x_arr))
    # --------------------------------------------
    # HINT: Should look like
    for i in range(self.degree + 1):
        p_x_arr += self.coeff[i]*(x_arr**i)
    # --------------------------------------------

    # remember 1: length = degree + 1 for a polynomial
    # remember 2: range(0, a) is same as range(a)
    # remember 3: range(a, b) means a is inclusive, b is exclusive

    # --------------------------------------------
    # YOUR CODE HERE -- Brute Force method
    # p_x = 0
    # for i in range(len(x_arr)):
    #     for ii in range(len(coeff)):
    #         p_x += coeff[ii]*(x_arr[i]**ii)
    #     p_x_arr.append(p_x)
    #     p_x = 0


    return p_x_arr
    # --------------------------------------------

  # String representation method of the object (similar to toString() of java)
  def __repr__(self):
    # remember: a formatted string must start with f.

    str_ret = f'Polynomial of degree {self.degree}\np(x) = '
    for i in range(self.degree + 1):
        a_val = self.coeff[i]
        if i != 0:
            if a_val >= 0:
                str_ret += f'+ {a_val}x^{i} '
            else:
                str_ret += f'- {-a_val}x^{i} '
        else:
            str_ret += f'{a_val}x^{i} '

    return str_ret

  # custom method 1: to get the degree of the polynomial
  def get_degree(self):
    # --------------------------------------------
    # YOUR CODE HERE
    return self.degree
    # --------------------------------------------

  # custom method 2: to get the coefficients of the polynomial
  def get_coeffs(self):
    # --------------------------------------------
    # YOUR CODE HERE
    return self.coeff

    # --------------------------------------------

In [5]:
def get_poly(data_x, data_y):
    n_nodes = len(data_x)
    # np.zeors((a, b)) returns a (a x b) matrix, i.e., a rows and b columns
    X = np.zeros((n_nodes, n_nodes)) #6*6


    # Populate the X matrix with appropriate values
    # YOUR CODE HERE
    for i in range(n_nodes):
        for ii in range(n_nodes):
            X[i][ii] = data_x[i]**ii

    print(X)
    # --------------------------------------------
    # np.linalg.inv is used to find the inverse
    # but pinv is more efficient
    X_inv = np.linalg.pinv(X) # pseudo inverse  #a = inv(X)*y
    a = np.dot(X_inv, data_y)
    p = Polynomial(a)

    return p
data_x = np.array([-0.65, 0.56, 1.5, -0.79])
data_y = np.array([1.73, 1.93, 2.74, 1.42])
p=get_poly(data_x, data_y)

x_arr = np.array([7])
test = p(x_arr)
print(test)

[[ 1.       -0.65      0.4225   -0.274625]
 [ 1.        0.56      0.3136    0.175616]
 [ 1.        1.5       2.25      3.375   ]
 [ 1.       -0.79      0.6241   -0.493039]]
[236.8691001]
